logging:
  level:
    com:
      example:
        openfeignspringtutorial:
          openfeign: DEBUG

feign:
  client:
    config:
      fake-api:
        logger-level: basic

application:
  feign-url:
    fake-api: https://jsonplaceholder.typicode.com
